# Generated by Django 3.1.5 on 2021-01-26 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_titel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='titel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.titel'),
        ),
    ]
