# Generated by Django 3.1.5 on 2021-01-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leverandoer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Leverandører',
            },
        ),
    ]
