# Generated by Django 3.1.5 on 2021-01-26 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arkiveringsversioner', '0002_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arkiveringsversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avid', models.CharField(max_length=5)),
                ('version', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=1)),
                ('jnr', models.CharField(blank=True, max_length=32, unique=True)),
                ('titel', models.CharField(blank=True, max_length=255)),
                ('kategori', models.CharField(blank=True, choices=[('Statslig', 'Statslig'), ('Kommunal', 'Kommunal'), ('Privat', 'Privat'), ('Klassificeret', 'Klassificeret'), ('Forskningsdata', 'Forskningsdata')], max_length=255, null=True)),
                ('klassifikation', models.CharField(blank=True, choices=[('Ingen', 'Ingen'), ('Til tjenestebrug', 'Til tjenestebrug')], default='Ingen', max_length=255, null=True)),
                ('land', models.CharField(blank=True, choices=[('Danmark', 'Danmark'), ('Grønland', 'Grønland')], default='Danmark', max_length=8, null=True)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arkiveringsversioner.type')),
            ],
            options={
                'verbose_name_plural': 'arkiveringsversioner',
            },
        ),
    ]
