# Generated by Django 3.1.5 on 2021-01-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkiveringsversioner', '0003_arkiveringsversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Statusser',
            },
        ),
        migrations.AlterModelOptions(
            name='arkiveringsversion',
            options={'verbose_name_plural': 'Arkiveringsversioner'},
        ),
        migrations.AlterField(
            model_name='arkiveringsversion',
            name='kategori',
            field=models.CharField(blank=True, choices=[('Statslig', 'Statslig'), ('Kommunal', 'Kommunal'), ('Privat', 'Privat'), ('Forskningsdata', 'Forskningsdata')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='arkiveringsversion',
            name='klassifikation',
            field=models.CharField(blank=True, choices=[('Ingen', 'Ingen'), ('Til tjenestebrug', 'Til tjenestebrug'), ('Andet', 'Andet')], default='Ingen', max_length=255, null=True),
        ),
    ]
