# Generated by Django 3.1.5 on 2021-01-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkiveringsversioner', '0005_auto_20210126_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Statusser',
            },
        ),
    ]
