# Generated by Django 3.1.5 on 2021-01-26 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arkiveringsversioner', '0007_status_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='arkiveringsversion',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arkiveringsversioner.status'),
        ),
    ]
