# Generated by Django 3.1.5 on 2021-01-26 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arkiveringsversioner', '0008_arkiveringsversion_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arkiveringsversion',
            name='arkivar_noter',
        ),
        migrations.RemoveField(
            model_name='arkiveringsversion',
            name='status',
        ),
        migrations.RemoveField(
            model_name='arkiveringsversion',
            name='tester_noter',
        ),
        migrations.RemoveField(
            model_name='arkiveringsversion',
            name='version',
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=1)),
                ('arkivar_noter', models.TextField(blank=True, null=True)),
                ('tester_noter', models.TextField(blank=True, null=True)),
                ('afleveringsfrist', models.DateField(blank=True, null=True)),
                ('modtaget', models.DateField(blank=True, null=True)),
                ('adgang', models.DateField(blank=True, null=True)),
                ('svarfrist', models.DateField(blank=True, null=True)),
                ('svar', models.DateField(blank=True, null=True)),
                ('avid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkiveringsversioner.arkiveringsversion')),
                ('leverandoer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arkiveringsversioner.leverandoer')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arkiveringsversioner.status')),
            ],
            options={
                'verbose_name_plural': 'Versioner',
            },
        ),
    ]
