# Generated by Django 3.1.5 on 2021-01-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkiveringsversioner', '0009_auto_20210126_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='arkivar_noter',
        ),
        migrations.RemoveField(
            model_name='version',
            name='tester_noter',
        ),
        migrations.AddField(
            model_name='arkiveringsversion',
            name='arkivar_noter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arkiveringsversion',
            name='tester_noter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
