# Generated by Django 3.1.5 on 2021-01-27 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20210127_1256'),
        ('arkiveringsversioner', '0011_auto_20210126_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='journaliseret',
        ),
        migrations.RemoveField(
            model_name='version',
            name='kopieret',
        ),
        migrations.RemoveField(
            model_name='version',
            name='kvitteret',
        ),
        migrations.AddField(
            model_name='version',
            name='tester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.bruger'),
        ),
        migrations.AlterField(
            model_name='arkiveringsversion',
            name='kategori',
            field=models.CharField(blank=True, choices=[('Statslig', 'Statslig'), ('Kommunal', 'Kommunal'), ('Privat', 'Privat'), ('Forskning', 'Forskning')], max_length=255, null=True),
        ),
    ]
