# Generated by Django 3.1.5 on 2021-01-27 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20210127_1256'),
        ('arkiveringsversioner', '0012_auto_20210127_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='arkivar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arkivar', to='system.bruger'),
        ),
        migrations.AlterField(
            model_name='version',
            name='tester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tester', to='system.bruger'),
        ),
    ]
