# Generated by Django 3.1.5 on 2021-01-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkiveringsversioner', '0013_auto_20210127_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='status',
        ),
        migrations.AddField(
            model_name='version',
            name='corona',
            field=models.BooleanField(default=False),
        ),
    ]
