# Generated by Django 3.1.5 on 2021-01-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkiveringsversioner', '0014_auto_20210128_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='status',
            field=models.CharField(choices=[('Afventer aflevering', 'Afventer aflevering'), ('Modtaget', 'Modtaget'), ('Under test', 'Under test'), ('Tilbagemeldt', 'Tilbagemeldt'), ('Afventer genaflevering', 'Afventer genaflevering'), ('Godkendt af tester', 'Godkendt af tester'), ('Godkendt', 'Godkendt')], default='Afventer aflevering', max_length=32),
        ),
    ]
