# Generated by Django 3.1.5 on 2021-01-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkiveringsversioner', '0017_remove_version_tilbagemeldt_afleveringsfrist_opdateret'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='modtaget_ikke_krypteret',
            field=models.BooleanField(default=False),
        ),
    ]
