# Generated by Django 3.1.5 on 2021-02-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkiveringsversioner', '0020_auto_20210128_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='stoerrelse',
            new_name='stoerrelsegb',
        ),
        migrations.AddField(
            model_name='version',
            name='stoerrelsemb',
            field=models.IntegerField(default=0, verbose_name='Størrelse i MB'),
        ),
    ]
