# Generated by Django 3.1.5 on 2021-02-01 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arkiveringsversioner', '0021_auto_20210201_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='stoerrelsegb',
        ),
    ]
