# Generated by Django 3.1.5 on 2021-02-01 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arkiveringsversioner', '0024_remove_version_godkendt_af_tester_parat_til_godkendelse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='godkendt_af_tester_nedpakket',
        ),
    ]
