# Generated by Django 3.1.5 on 2021-02-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkiveringsversioner', '0025_remove_version_godkendt_af_tester_nedpakket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helligdag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dag', models.DateField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Helligdage',
            },
        ),
        migrations.AlterField(
            model_name='version',
            name='status',
            field=models.CharField(choices=[('Afventer aflevering', 'Afventer aflevering'), ('Modtaget', 'Modtaget'), ('Klar til test', 'Klar til test'), ('Under test', 'Under test'), ('Tilbagemeldt', 'Tilbagemeldt'), ('Afventer genaflevering', 'Afventer genaflevering'), ('Godkendt af tester', 'Godkendt af tester'), ('Parat til godkendelse', 'Parat til godkendelse'), ('Godkendt', 'Godkendt'), ('Afsluttet', 'Afsluttet')], default='Afventer aflevering', max_length=32),
        ),
    ]
