# Generated by Django 3.1.5 on 2021-02-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkiveringsversioner', '0026_auto_20210224_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='genafleveringsfrist',
            field=models.DateField(blank=True, null=True),
        ),
    ]
