# Generated by Django 3.1.5 on 2021-02-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkiveringsversioner', '0027_version_genafleveringsfrist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkiveringsversion',
            name='public',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
