# Generated by Django 3.1.5 on 2021-02-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkiveringsversioner', '0028_auto_20210225_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkiveringsversion',
            name='jnr',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
