# Generated by Django 3.1.5 on 2021-02-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkiveringsversioner', '0031_auto_20210226_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkiveringsversion',
            name='avid',
            field=models.IntegerField(unique=True),
        ),
    ]
