# Generated by Django 3.1.5 on 2021-03-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkiveringsversioner', '0033_auto_20210301_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkiveringsversion',
            name='kategori',
            field=models.CharField(blank=True, choices=[('Statslig', 'Statslig'), ('', 'Kommunal'), ('Privat', 'Privat'), ('Forskning', 'Forskning')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='arkiveringsversion',
            name='public',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
