# Generated by Django 3.1.5 on 2021-04-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkiveringsversioner', '0034_auto_20210303_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='modtaget_ada_startet',
            field=models.BooleanField(default=False),
        ),
    ]
