# Generated by Django 3.1.5 on 2021-01-19 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(blank=True, max_length=255)),
                ('producent', models.CharField(blank=True, max_length=255)),
                ('kapacitet', models.IntegerField(default=0, verbose_name='Kapacitet i GB')),
                ('type', models.CharField(blank=True, choices=[('Solid State Drive', 'Solid State Drive'), ('Hard Drive 3.5', 'Hard Drive 3.5'), ('Hard Drive 2.5', 'Hard Drive 2.5'), ('USB Stick', 'USB Stick'), ('Ekstern SSD (USB)', 'Ekstern SSD (USB)'), ('Ekstern NVMe (USB)', 'Ekstern NVMe (USB)'), ('Ekstern Hard Drive (USB)', 'Ekstern Hard Drive (USB)')], max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Medier',
            },
        ),
        migrations.CreateModel(
            name='Placering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokation', models.CharField(blank=True, choices=[('København', 'København'), ('Odense', 'Odense')], max_length=255, null=True)),
                ('lokale', models.CharField(blank=True, choices=[('BLABLA01', 'Testværksted'), ('BLABLA02', 'Dataværksted'), ('BLABLA03', 'Kontor BLABLA03')], max_length=255, null=True)),
                ('netvaerk', models.CharField(blank=True, choices=[('SIT', 'SIT'), ('ARKNET', 'ARKNET'), ('Udvikling', 'Udvikling')], max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Placeringer',
            },
        ),
        migrations.CreateModel(
            name='Maskine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(blank=True, max_length=255)),
                ('processor', models.CharField(blank=True, max_length=255)),
                ('bundkort', models.CharField(blank=True, max_length=255)),
                ('arbejdshukommelse', models.IntegerField(default=0, verbose_name='Arbejdshukommelse i GB')),
                ('type', models.CharField(blank=True, choices=[('Server', 'Server'), ('Desktop', 'Desktop'), ('Laptop', 'Laptop')], max_length=255)),
                ('kommentar', models.TextField(blank=True)),
                ('placering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.placering')),
            ],
            options={
                'verbose_name_plural': 'Maskiner',
            },
        ),
    ]
