# Generated by Django 3.1.5 on 2021-04-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkiveringsversioner', '0034_auto_20210303_1442'),
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medie',
            name='arkiveringsversion',
            field=models.ManyToManyField(blank=True, related_name='arkiveringsversioner', to='arkiveringsversioner.Arkiveringsversion'),
        ),
    ]
