# Generated by Django 3.1.5 on 2021-04-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkiveringsversioner', '0034_auto_20210303_1442'),
        ('hardware', '0003_auto_20210425_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medie',
            name='arkiveringsversioner',
        ),
        migrations.AddField(
            model_name='medie',
            name='versioner',
            field=models.ManyToManyField(blank=True, related_name='versioner', to='arkiveringsversioner.Version'),
        ),
    ]
